//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemas2001.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento
    {
        public string ID { get; set; }
        public int ID_Fila_Asiento { get; set; }
        public int Num_Asiento { get; set; }
        public string ID_Sala { get; set; }
        public Nullable<bool> Disponibilidad { get; set; }
    
        public virtual Fila_Asiento Fila_Asiento { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
