//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemas2001.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento_Horario
    {
        public int id_Asiento_Horario { get; set; }
        public int id_Asiento { get; set; }
        public int id_Horario { get; set; }
        public bool Disponibilidad { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual Horario Horario { get; set; }
    }
}
